services:
  - type: web
    name: edupath-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: RESEARCH_MODEL_NAME
        value: groq/compound-mini
      - key: QA_MODEL_NAME
        value: groq/compound-mini
